const nino = '/images/nino.svg'; // Assuming you have nino.svg in public/images/
const nika = '/images/nika.svg';
const nugo = '/images/nugo.svg';
const graphic = '/images/graphic.jpg';
const music = '/images/music.jpg';
const pi = '/images/pi.jpg';

const services = [
  {
    id: 1,
    img: pi,
    avatar: nino,
    category: 'Tutoring',
    subCategory: 'Math',
    title: 'Private math lessons',
    desc: 'Tutoring high schoolers in Math',
    tier: 'Tier 2',
    price: '200L',
    name: 'Nino',
    Number: '558292521',
  },
  {
    id: 2,
    img: graphic,
    avatar: nika,
    category: 'Design',
    subCategory: 'Graphic design',
    title: 'Experienced graphic designer',
    desc: 'Creative graphic designer specializing in developing visually appealing templates for various products.',
    tier: 'Tier 3',
    price: 'TBD',
    name: 'Nika',
    Number: '558292125',
  },
  {
    id: 3,
    img: music,
    avatar: nugo,
    category: 'Tutoring',
    subCategory: 'Music',
    title: "Nugo, let's go!",
    desc: 'I will make you fall in love with guitar',
    tier: 'Tier 1',
    price: '100L',
    name: 'Nugo',
    Number: '558252129',
  },
  {
    id: 4,
    img: graphic,
    avatar: nika,
    category: 'Design',
    subCategory: 'Graphic design',
    title: 'Experienced graphic designer',
    desc: 'Creative graphic designer specializing in developing visually appealing templates for various products.',
    tier: 'Tier 3',
    price: 'TBD',
    name: 'Nika',
    Number: '555144159',
  },
  {
    id: 5,
    img: pi,
    avatar: nino,
    category: 'Tutoring',
    subCategory: 'Math',
    title: 'Private math lessons',
    desc: 'Tutoring high schoolers in Math',
    tier: 'Tier 2',
    price: '200L',
    name: 'Nino',
    Number: '558292521',
  },
  {
    id: 6,
    img: graphic,
    avatar: nika,
    category: 'Design',
    subCategory: 'Graphic design',
    title: 'Experienced graphic designer',
    desc: 'Creative graphic designer specializing in developing visually appealing templates for various products.',
    tier: 'Tier 3',
    price: 'TBD',
    name: 'Nika',
    Number: '558292125',
  },
  {
    id: 7,
    img: music,
    avatar: nugo,
    category: 'Tutoring',
    subCategory: 'Music',
    title: "Nugo, let's go!",
    desc: 'I will make you fall in love with guitar',
    tier: 'Tier 1',
    price: '100L',
    name: 'Nugo',
    Number: '558252129',
  },
  {
    id: 8,
    img: graphic,
    avatar: nika,
    category: 'Design',
    subCategory: 'Graphic design',
    title: 'Experienced graphic designer',
    desc: 'Creative graphic designer specializing in developing visually appealing templates for various products.',
    tier: 'Tier 3',
    price: 'TBD',
    name: 'Nika',
    Number: '555144159',
  },
];

export default services;
